### ISSUE TITLE
Ripples.js triggers multiple click events to angular file upload

### ISSUE THREAD

**Issue by JuhQ** [mdbootstrap/mdb-ui-kit#230]
It seems that using bootstrap material design ripples.js triggers multiple clicks on ngFileSelect directive in [angular-file-upload](https://github.com/danialfarid/angular-file-upload)

Issue also opened in their issue tracker
danialfarid/angular-file-upload#415

**Comment by ghost** [comment]
Also with http://filedropjs.org
The error given from FileDrop is "Browser does not support HTML5 drag and drop"

**Comment by FezVrasta** [comment]
may you provide a demo? Use http://codepen.io/FezVrasta/pen/ihmea

**Comment by FezVrasta** [comment]
This bug should be fixed with fc0fed6eabec91e4535d78d06478a25c1fff67ce (:develop branch)

May you try it out and give me feedbacks?

**Comment by FezVrasta** [comment]
I consider it fixed because the OP has not replied...

**Comment by andypmw** [comment]
Hi @FezVrasta 

I use Bootstrap Material Design and Angular Upload. Exactly same.

I have paste the sample code on you Codepen.

I have tried this >> fc0fed6 (:develop branch)

But the problem still occured.

Look at my browser console screenshoot. The file uploaded several times. It should be only sent one time. 

![ripple](https://cloud.githubusercontent.com/assets/2743194/5580187/75406ee6-9079-11e4-84fa-04674029763e.JPG)

**Comment by andypmw** [comment]
Ouya @FezVrasta 

I tried remove the ripple.js from HTML page. And this bug still occured.

And then I tried remove only the material.js from HTML page. And voila, the bug was gone!

![ripple2](https://cloud.githubusercontent.com/assets/2743194/5580284/d9df177a-907a-11e4-9767-ab7a7beb1f98.JPG)

**Comment by andypmw** [comment]
Here the sample code :+1: 

http://codepen.io/andyprimawan/pen/yyamqj?editors=101

**Comment by FezVrasta** [comment]
try with:

```
$.material.options.autofill = false;
$.material.init();
```

it should do the trick

**Comment by andypmw** [comment]
COOL!

The problem is gone now!

Thank you @FezVrasta
