### ISSUE TITLE
Links with .btn class are not working in iPhone

### ISSUE THREAD

**Issue by rougin** [mdbootstrap/mdb-ui-kit#26]
Hello again! After the previous issue https://github.com/FezVrasta/bootstrap-material-design/issues/24 has been fixed, I also found out that links with `.btn` class are not working. I tried to insert a "target" attribute but still the problem exists. If i remove the said class, it works just as it should.

![image](https://cloud.githubusercontent.com/assets/6078637/4333548/eb9312e4-3fe1-11e4-9705-0d833222b87c.png)

**Comment by rougin** [comment]
The problem also exists in button dropdowns as well (including the `.navbar`).

**Comment by FezVrasta** [comment]
which browser?

**Comment by rougin** [comment]
In Chrome and Safari browsers.

**Comment by FezVrasta** [comment]
Ok probably is the same bug which affects Firefox on desktop... will try to apply the same fix.

**Comment by FezVrasta** [comment]
@rougin may you try the latest version? It should be fixed.

**Comment by pixelyunicorn** [comment]
The same issue still shows up on your demo page using Safari for Mac and iOS.

**Comment by FezVrasta** [comment]
I've not updated the demo I'm sorry

**Comment by rougin** [comment]
It works now and also with the showing of modals. Tested on Chrome and Safari. :+1:

**Comment by FezVrasta** [comment]
Ok so.. reading LabLayers' message seems like the problem exists even on the desktop version of Safari, can someone confirm it?

**Comment by rougin** [comment]
I'm using Chrome on Linux in desktop by the way.

**Comment by FezVrasta** [comment]
Ok, wait for someone which can confirm the bug affects OSX as well... If possible let me know even if the problem affects Chrome on OSX.

**Comment by pixelyunicorn** [comment]
Can confirm, this affects Safari on OSX: http://quick.as/xg2s6db

**Comment by FezVrasta** [comment]
fixed
