### ISSUE TITLE
input effects not working

### ISSUE THREAD

**Issue by donatopellegrino** [mdbootstrap/mdb-ui-kit#593]
Hi everyone.
I'm using this fantastic theme to make a presentation for my school exams.
Every effect works, except the effect that should appear when you click on an input.
It becomes directly underlined without any effect.
How can i do?
I'm working using google chrome
here my code:
![cattura di schermata 4](https://cloud.githubusercontent.com/assets/12414940/7593069/a4b1fbba-f8d7-11e4-9a4c-ee0082793ad0.png)

**Comment by eweseong** [comment]
Hi Could you create a fiddle to replicate the issue? http://jsfiddle.net/wht5Lns6/ this fiddle seems to work fine, it could it part of your own css/javascript that is causing the issue.

**Comment by Klakurka** [comment]
I actually have this same issue using the _sample_ code (https://github.com/FezVrasta/bootstrap-material-design/archive/master.zip). In addition, the other inputs are also not working as expected. The on-click animations seem to work fine but both toggled states show at once.

For me, that fiddle doesn't work at all -- not even any of the styles apply on run...

![uiissues](https://cloud.githubusercontent.com/assets/4713204/7625679/d70a50a2-f9af-11e4-8751-964bc286007c.png)

**Comment by Klakurka** [comment]
Refer to this commit...

https://github.com/FezVrasta/bootstrap-material-design/commit/56a6d8d8ee5326a3e1f1ab067011411b8c6acf66

It looks like the input underlining animation, at the very least, was broken and never fixed...

**Comment by eweseong** [comment]
If you look closer it is not broken, the animation was removed and replaced by transition. I have a project using the latest master and I'm not facing any issue with the animations.

**Comment by Klakurka** [comment]
Steps to recreate:
1. From master, copy contents of 'dist' into working directory.
2. Add the markup for the example form found on this page: https://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html (everything within 'div class="well bs-component"') somewhere on the page (test.html).

The end result, for me (refer to screenshot above), is as follows:
- Checkboxes and radio buttons are duplicated (side-by-side), but only the first (left) elements are toggle-able.
- Bottom border on-click animation is not present on text inputs.
- All other styles / functionality seem to work as expected.

**Comment by FezVrasta** [comment]
You have to copy the markup provided by the source button, not through inspector

**Comment by Klakurka** [comment]
Thanks.

The checkboxes and radio buttons work as expected.

The input element bottom border on-click animation, however, still does not work in my testing.

**Comment by Klakurka** [comment]
As mentioned in that commit I linked, replacing:

```
 transition: background 0 ease-out;
```

with

```
 transition: background 0s ease-out;
```

resolves the issue.

**Comment by donatopellegrino** [comment]
ok thank you very much.
i solved the problem replacing (as recommended by Klakurka)
"transition: background 0 ease-out;"
with
"transition: background 0s ease-out;"
in the file material-fullpalette.min.css

**Comment by FezVrasta** [comment]
Isn't it already fixed in master? I thought I had merged a PR about that

**Comment by Klakurka** [comment]
It looks like it still exists in master, at least last time I checked (2 days ago).
