### ISSUE TITLE
Weird inputs transitions on focus

### ISSUE THREAD

**Issue by jgoux** [mdbootstrap/mdb-ui-kit#9]
Hi,
on Chrome/Firefox, both last version, there is a "square" which appears during the transition when I focus on an input.
![paper](https://cloud.githubusercontent.com/assets/1443499/4178691/57f3972c-36a2-11e4-9eb5-12e84fc665e5.gif)

**Comment by FezVrasta** [comment]
Emh yes this is the correct behavior... It's the way the paper inputs looks like.

**Comment by roeku** [comment]
There does seem to be something wrong with the first input element though, I noticed it too in my chrome browser, thought it was a glitch. 

After the effect should end the box reappears for a moment.

**Comment by jgoux** [comment]
Indeed. I didn't know. It really feels it's a repaint bug or something. Weird choice from Google.
Could you add an optional class to hide the square and only animate the line ?

**Comment by FezVrasta** [comment]
@roeku: I see, it happens sometimes, I think it's some rendering issue... hope to can do something to fix it.

@jgoux: This project is thought to be a 1:1 transposition of the paper elements (material design), if you want to disable that effect you can just add this to your CSS:

```
.material-input:after { display: none; }
```

**Comment by roeku** [comment]
Perhaps the animation could also stop at the cursors position. The animation indicates where you'll input will start. The guys at [polymer](http://www.polymer-project.org/components/paper-elements/demo.html#paper-input) adjusted it too.

**Comment by FezVrasta** [comment]
I've fixed the animation position and tried to fix the animation glitch but I'm not sure I've fixed it, seems sometimes it happens, but not so often.

**Comment by roeku** [comment]
Position looks good, but the glitch still appears to be there. But you're right it doesn't happen all the time.
