### ISSUE TITLE
v4 build error

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#951]
> I'm using the scss files through an @import and that's where the issue occurred. I have tried replicating this issue in this repository; however, I am unable to get it to work. I expected that it should be just a matter of

```
$ npm install
$ bower install
$ bundle install
$ gulp
```

but it fails with

`Unable to find Rails application directory based on existence of 'bin/rails'`

https://github.com/FezVrasta/bootstrap-material-design/pull/949#issuecomment-202445457

cc: @JP-Ellis

**Comment by rosskevin** [comment]
Looking at this now.  Just a note, bower is unneeded in v4

**Comment by JP-Ellis** [comment]
I saw that `bower.json` was there, so I simply ran it in case it was needed.

**Comment by rosskevin** [comment]
please run `npm ls gulp-pipeline`

**Comment by JP-Ellis** [comment]
```
$ npm ls gulp-pipeline
bootstrap-material-design@4.0.1 /tmp/bootstrap-material-design
└── gulp-pipeline@4.0.19 
```

**Comment by rosskevin** [comment]
Docs are on a more complete site now (tmp url), but we may need to bring some essentials back to the readme:
http://rosskevin.github.io/bootstrap-material-design/getting-started/build-tools/

I should have this resolved shortly, I maintain that dependency.  I was on 4.0.13

**Comment by rosskevin** [comment]
It's probably about time to enable travis, it's been off.

```
git pull && npm install && gulp
```

should get you building again.

**Comment by rosskevin** [comment]
4.0.20 is the fixed gulp-pipeline, please confirm you are building.

**Comment by rosskevin** [comment]
Docs fixed with d61942b2981e4bf596c44e3253c58bbf21b77b01

**Comment by JP-Ellis** [comment]
Hmm, this still doesn't work for me, though I'm not sure the error is due to the gulpfile or whether it is an error in gulp itself.

Here's exactly what I have done:

``` sh
$ git clone git@github.com:FezVrasta/bootstrap-material-design.git --branch v4-dev --depth 1
$ cd bootstrap-material-design
$ rm Gemfile.lock
$ echo 2.3.0 > .ruby-version
$ bundle install; npm install; gulp
# usually output
[12:38:53] Requiring external module babel-register
[12:38:54] Using gulpfile /tmp/bootstrap-material-design/gulpfile.babel.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:142:18)
    at node.js:939:3
```

Note that I'm removing `Gemfile.lock` because Bundler fails to find `rb-inotify-0.9.6` otherwise, and I have to switch to version `2.3.0` of Ruby because I am unable to install `2.2.2` (the compilation consistently fails).  In both cases though, this should be the cause of the issue.

Also for the sake of debugging:

```
$ npm ls --depth 0
bootstrap-material-design@4.0.1 /tmp/bootstrap-material-design
├── babel-core@6.7.4
├── babel-eslint@6.0.0
├── babel-polyfill@6.7.4
├── babel-preset-es2015@6.6.0
├── bootstrap@4.0.0-alpha.2 (git://github.com/twbs/bootstrap.git#064fda0e802679e56e88db2910fdf5369dde6e4c)
├── extend@3.0.0
├── gulp@4.0.0-alpha.2 (git://github.com/gulpjs/gulp.git#1e7728f1792d893ccd06c854c453dfa35e256577)
├── gulp-pipeline@4.0.22
├── jquery@2.2.2
├── moment@2.12.0
└── tether@1.2.0
```

**Comment by rosskevin** [comment]
Check the readme for the link to "Building".  My guess is that you aren't using the right global gulp-cli package (it's the 4.0 branch).

**Comment by JP-Ellis** [comment]
Oh, that is indeed the issue.  Thanks!
